

### Clock signal
#set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { clkin100 }]; #IO_L12P_T1_MRCC_35 Sch=gclk[100]
create_clock -period 5.000 -name clk200 -waveform {0.000 2.500} [get_ports clk_in200_p]
create_clock -period 7.500 -name Pclk_p -waveform {0.000 3.750} [get_ports Pclk_p]

#Vitraul clock driving data from ADC
create_clock -period 1.875 -name ADC_DATA_CLK -waveform {0.000 0.9375}
set_input_delay -clock [get_clocks ADC_DATA_CLK]  -min -add_delay -0.200 [get_ports CH_p[79:0]]
set_input_delay -clock [get_clocks ADC_DATA_CLK]  -max -add_delay  0.200 [get_ports CH_p[79:0]]
#asynchronous groups
set_clock_groups -asynchronous -group [get_clocks ADC_DATA_CLK] -group [get_clocks Pclk_p]

#
#There are three singnals which I pass from module LUX13HS_control (domain 'Pclk') to domain 'Pclk_x4_shifted' in this module.
#These signals are 'st_readb_n', 'st_readt_n' and 'row_address'. The signals 'st_readb_n' and 'st_readt_n' are use for control of starting 
#readout: when they have changed I check the 'row_address' and calculate my internal addresses 'row_address_bot' and 'row_address_top'. 
#I do synchronization for 'st_readb_n' and 'st_readt_n' only because 'row_address' changes very slowly and long time before changing 
#'st_readb_n' and 'st_readt_n'. So, I suppose that 'row_address' have quite relaxed to this moment.

#The same situation is with 'read_bot_locked' singnal which is used between full frame sequential readings to stop internal counting.
#The moment when it is setting is 'enable_read_bot_strb_del' and 'row_address' must be relaxed to this time.
#So I expect that I can use 'set_clock_groups -asynchronous' constraint between 'Pclk' and 'Pclk_x4_shifted' domains.

#NOTICE: It's seems more safety and simple to move LUX13HS_control from 'Pclk' domain to 'Pclk_x4_shifted' domain to workaround this problem.
#

set_clock_groups -asynchronous -group [get_clocks clk_out4_clk_wiz_2xPclk] -group [get_clocks clk_out3_clk_wiz_2xPclk] -group [get_clocks Pclk_p]





set_property PACKAGE_PIN H11 [get_ports Pclk_p]





set_property PACKAGE_PIN H12 [get_ports clk_in100]
set_property PACKAGE_PIN G12 [get_ports clk_lux]


set_false_path -from [get_pins LUX13HS_ADC_readout/Pclk/inst/mmcme3_adv_inst/CLKOUT3] -to [get_pins LUX13HS_ADC_readout/Pclk_sync1_reg/D]



set_property IOSTANDARD SSTL135_DCI [get_ports mii_rx_clk]
set_property IOSTANDARD LVDS [get_ports {CH_n[79]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[78]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[77]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[76]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[75]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[74]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[73]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[72]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[71]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[70]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[69]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[68]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[67]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[66]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[65]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[64]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[63]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[62]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[61]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[60]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[59]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[58]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[57]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[56]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[55]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[54]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[53]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[52]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[51]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[50]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[49]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[48]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[47]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[46]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[45]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[44]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[43]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[42]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[41]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[40]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[39]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[38]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[37]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[36]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[35]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[34]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[33]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[32]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[31]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[30]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[29]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[28]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[27]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[26]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[25]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[24]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[23]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[22]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[21]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[20]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[19]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[18]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[17]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[16]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[15]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[14]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[13]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[12]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[11]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[10]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[9]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[8]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[7]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[6]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[5]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[4]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[3]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[2]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[1]}]
set_property IOSTANDARD LVDS [get_ports {CH_n[0]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[79]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[78]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[77]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[76]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[75]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[74]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[73]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[72]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[71]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[70]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[69]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[68]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[67]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[66]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[65]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[64]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[63]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[62]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[61]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[60]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[59]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[58]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[57]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[56]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[55]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[54]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[53]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[52]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[51]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[50]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[49]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[48]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[47]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[46]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[45]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[44]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[43]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[42]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[41]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[40]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[39]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[38]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[37]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[36]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[35]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[34]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[33]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[32]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[31]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[30]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[29]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[28]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[27]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[26]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[25]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[24]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[23]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[22]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[21]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[20]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[19]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[18]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[17]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[16]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[15]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[14]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[13]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[12]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[11]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[10]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[9]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[8]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[7]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[6]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[5]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[4]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[3]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[2]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[1]}]
set_property IOSTANDARD LVDS [get_ports {CH_p[0]}]

#set_property INTERNAL_VREF 0.675 [get_iobanks 67]
set_property IOSTANDARD LVDS [get_ports Pclk_p]



set_property PROHIBIT true [get_bels IOB_X0Y12/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y0/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y1/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y2/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y3/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y4/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y5/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y6/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y7/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y8/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y9/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y10/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y11/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y25/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y13/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y14/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y15/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y16/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y17/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y18/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y19/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y20/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y21/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y22/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y23/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y24/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y38/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y26/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y27/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y28/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y29/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y30/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y31/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y32/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y33/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y34/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y35/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y36/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y37/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y51/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y39/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y40/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y41/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y42/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y43/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y44/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y45/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y46/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y47/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y48/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y49/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y50/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y116/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y104/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y105/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y106/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y107/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y108/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y109/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y110/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y111/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y112/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y113/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y114/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y115/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y129/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y117/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y118/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y119/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y120/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y121/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y122/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y123/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y124/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y125/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y126/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y127/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y128/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y142/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y130/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y131/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y132/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y133/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y134/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y135/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y136/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y137/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y138/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y139/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y140/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y141/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y155/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y143/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y144/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y145/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y146/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y147/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y148/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y149/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y150/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y151/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y152/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y153/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y154/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y168/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y156/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y157/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y158/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y159/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y160/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y161/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y162/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y163/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y164/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y165/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y166/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y167/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y181/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y169/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y170/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y171/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y172/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y173/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y174/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y175/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y176/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y177/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y178/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y179/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y180/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y194/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y182/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y183/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y184/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y185/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y186/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y187/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y188/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y189/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y190/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y191/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y192/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y193/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y207/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y195/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y196/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y197/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y198/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y199/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y200/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y201/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y202/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y203/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y204/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y205/PAD]
set_property PROHIBIT true [get_bels IOB_X1Y206/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y64/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y77/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y90/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y103/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y53/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y52/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y55/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y54/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y57/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y56/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y59/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y58/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y61/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y60/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y63/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y62/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y66/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y65/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y68/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y67/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y70/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y69/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y72/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y71/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y74/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y73/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y79/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y78/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y81/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y80/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y83/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y82/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y85/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y84/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y87/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y86/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y89/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y88/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y92/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y91/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y94/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y93/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y95/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y96/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y98/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y97/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y100/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y99/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y102/PAD]
set_property PROHIBIT true [get_bels IOB_X0Y101/PAD]
